#!/bin/bash

# Copyright (C) 2016  Stefan Vargyas
# 
# This file is part of Hash-Trie.
# 
# Hash-Trie is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Hash-Trie is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Hash-Trie.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ hash-trie-gen-test -g test -T empty
#
[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L empty.old <(echo \
'$ test -x ./hash-trie
$ print() { printf '\''%s\n'\'' "$@"; }
$ hash-trie-config() { hash-trie -P|sed -r '\''/^(TOLERANCE|TRIE_SIZE):/!d'\''; }
$ hash-trie() { ./hash-trie "$@"; }
$ hash-trie-config
TOLERANCE:    1000
TRIE_SIZE:    32767
$ echo|hash-trie
hash-trie: error:1: hash tries cannot contain empty words
command failed: echo|hash-trie
$ echo -n|hash-trie'
) -L empty.new <(
echo '$ test -x ./hash-trie'
test -x ./hash-trie 2>&1 ||
echo 'command failed: test -x ./hash-trie'

echo '$ print() { printf '\''%s\n'\'' "$@"; }'
print() { printf '%s\n' "$@"; } 2>&1 ||
echo 'command failed: print() { printf '\''%s\n'\'' "$@"; }'

echo '$ hash-trie-config() { hash-trie -P|sed -r '\''/^(TOLERANCE|TRIE_SIZE):/!d'\''; }'
hash-trie-config() { hash-trie -P|sed -r '/^(TOLERANCE|TRIE_SIZE):/!d'; } 2>&1 ||
echo 'command failed: hash-trie-config() { hash-trie -P|sed -r '\''/^(TOLERANCE|TRIE_SIZE):/!d'\''; }'

echo '$ hash-trie() { ./hash-trie "$@"; }'
hash-trie() { ./hash-trie "$@"; } 2>&1 ||
echo 'command failed: hash-trie() { ./hash-trie "$@"; }'

echo '$ hash-trie-config'
hash-trie-config 2>&1 ||
echo 'command failed: hash-trie-config'

echo '$ echo|hash-trie'
echo|hash-trie 2>&1 ||
echo 'command failed: echo|hash-trie'

echo '$ echo -n|hash-trie'
echo -n|hash-trie 2>&1 ||
echo 'command failed: echo -n|hash-trie'
)

