#!/bin/bash

# Copyright (C) 2016  Stefan Vargyas
# 
# This file is part of Hash-Trie.
# 
# Hash-Trie is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Hash-Trie is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Hash-Trie.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ hash-trie-gen-test -g test -T help
#
[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L help.old <(echo \
'$ test -x ./hash-trie
$ print() { printf '\''%s\n'\'' "$@"; }
$ hash-trie-config() { hash-trie -P|sed -r '\''/^(TOLERANCE|TRIE_SIZE):/!d'\''; }
$ ./hash-trie -?
usage: hash-trie [OPTION]...
where the options are:
  -P|--[print-]config  action: print out the config parameters
  -T|--[print-]types   action: print out the add/sub types table
  -L|--load-only       action: only load the input into the hash trie
  -p|--print[-trie]    action: print out all <word, count> pairs from
                         the hash trie (default)
  -d|--dump[-trie]     action: dump out the complete hash trie structure
  -b|--[no-][dump-]backtrace
                       dump a backtrace of the program on fatal error
                         or otherwise do not (default not)
  -c|--[no-][print-]chars
                       print out characters instead of codes on structure
                         dumps or otherwise do not (default not)
  -w|--[no-][print-]words
                       print out words when dumping out the hash trie
                         or otherwise do not (default do)
     --debug=WHAT      print out some debugging information; WHAT can
                         be one of: probing
     --no-debug        do not print debugging info at all (default)
  -q|--[no-]quiet      be quiet or otherwise do not (default not)
  -v|--version         print version numbers and exit
  -?|--help            display this help info and exit'
) -L help.new <(
echo '$ test -x ./hash-trie'
test -x ./hash-trie 2>&1 ||
echo 'command failed: test -x ./hash-trie'

echo '$ print() { printf '\''%s\n'\'' "$@"; }'
print() { printf '%s\n' "$@"; } 2>&1 ||
echo 'command failed: print() { printf '\''%s\n'\'' "$@"; }'

echo '$ hash-trie-config() { hash-trie -P|sed -r '\''/^(TOLERANCE|TRIE_SIZE):/!d'\''; }'
hash-trie-config() { hash-trie -P|sed -r '/^(TOLERANCE|TRIE_SIZE):/!d'; } 2>&1 ||
echo 'command failed: hash-trie-config() { hash-trie -P|sed -r '\''/^(TOLERANCE|TRIE_SIZE):/!d'\''; }'

echo '$ ./hash-trie -?'
./hash-trie -? 2>&1 ||
echo 'command failed: ./hash-trie -?'
)

